Vagrant.configure("2") do |config|
  
  config.vm.box = "gusztavvargadr/windows-10"
  
  config.vm.provider "virtualbox" do |vb|
     vb.gui = false
     vb.memory = "1024"
     vb.name = "Koval_windows"
  end
end